### ISSUE TITLE
提个PR？

### ISSUE THREAD

**Issue by zhugeliange** [hjue/JustWriting#101]
你好，我非常喜欢您的这个系统，并准备以后都在这上面写博客了。
但是目前您的这个版本有一些bug，我尝试着修复并加了些自己的东西。[具体改动](https://github.com/zhugeliange/JustWriting)因为这个改动的稍微有点多，所以我就不提PR了，如有侵权或者冒犯的还烦请告知我 `arthursjy@gmail.com`

**Comment by hjue** [comment]
谢谢你喜欢这个系统 ，我很久不维护这个系统。
看到你增加了那么多功能，很棒 👍
