### ISSUE TITLE
404错误

### ISSUE THREAD

**Issue by craftor** [hjue/JustWriting#30]
新建md文件，首页可以看到，但是点击全文就会显示404错误。同样，打开tags、archives，都是404错误，请问是什么原因啊？
http://vps.craftor.org

**Comment by hnwy** [comment]
我用了那个配置文件，就是502

**Comment by hjue** [comment]
502 一般是服务器配置错误

 location ~* \.php {

                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_split_path_info ^(.+\.php)(/?.*)$;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

你是否安装好了php，并让他运行在9000端口？

**Comment by hnwy** [comment]
搞定，谢谢，果然是9000端口的问题。
已经全部搞定，目前把博客移到国外的VPS上，配置了btsync，绑定手机和电脑，这样即使不用dropbox，也能方便的写博客和修改了。
要总结下，走了很多弯路

**Comment by hjue** [comment]
:+1:
