### ISSUE TITLE
Using Justwriting ! (As a french guy ;) )

### ISSUE THREAD

**Issue by ncosnard** [hjue/JustWriting#49]
Hello ! I'm using justwriting for my blog [tictech](http://tictech.info)  
I've made a tutorial (in french) about installing it and uploading posts using git, you can get it [here](http://tictech.info/post/install_justwriting) if you are interested.

Just a little question by the way : is there a way to force post order when they are published the same day ?

Thanks for your work, it is awesome !

**Comment by hjue** [comment]
Thank you for your like.

The post order by the post date .You can set datetime in post meta with Date if they are published the same day.

ex:

    Date: 2015-1-3 12:00

**Comment by ncosnard** [comment]
Great thanks ! :+1:  I'm making tryouts, is there a way to put images in posts ?

**Comment by mkody** [comment]
@ncosnard It's Markdown, so add an image like this:
`![Google Logo](https://www.google.ch/images/srpr/logo11w.png)`

And the result will be
![Google Logo](https://www.google.ch/images/srpr/logo11w.png)

You can read Markdown documentation here: http://daringfireball.net/projects/markdown/syntax

**Comment by ncosnard** [comment]
Yup, but is there a way to have them integrated in justwriting files ?

**Comment by hjue** [comment]
also works with relative link.

You can put logo11w.png in the path called the images and then add an image like this:
![Google Logo](images/srpr/logo11w.png)

**Comment by ncosnard** [comment]
Thanks i'm gonna have a deeper look with that !
