### ISSUE TITLE
Tag weight

### ISSUE THREAD

**Issue by ncosnard** [hjue/JustWriting#50]
Hello !

I've made a custom template in which I have made a tag cloud, which you can see [here](http://tictech.info/tags). I had to tweak a bit jw core so I could be able to count the number of uses of each tag (weight) to give them different sizes.

I've modified `application/librairies/blog_lib.php` : 
Line 344 : 
Was : `$all_tags[$trimed_tag]=1;`
is now : `$all_tags[$trimed_tag]+=1;`

Line 423 : 
Was : `return array_keys($this->_all_tags);`
is now : `return $this->_all_tags;`

Changes only behaviour in tags page (other use get_posts() functions) and allows to sort tags with twig. I think it might interest some other people.

**Comment by JellyBool** [comment]
I changed modified `application/librairies/blog_lib.php` as you do , but i find it {{ tag }} become  the number of uses of each tag count, how can i dispaly tags like you do ?

**Comment by ncosnard** [comment]
It's because the tag name has become the key, and the number of uses the value. You simply need to change you `{% for %}` loop like this : 
```
{% for tag,weight in all_tags %}
    <p>{{ tag }} ({{ weight }} articles)</p>
{% endfor %}
```
This works pretty much like a PHP `foreach` loop

**Comment by JellyBool** [comment]
Thx
