### ISSUE TITLE
文章列表按什么排序的？

### ISSUE THREAD

**Issue by gede123** [hjue/JustWriting#53]
我能按照创建日期倒序吗?

**Comment by gdgoal** [comment]
刚才看了源码自己找到了，按照Position来排序的。但是排序貌似有问题？按照本意，貌似是按照Position倒序，或者发布日期倒序。但是其实表现出来的，恰好是正序。。。。为啥呢？因为，posts返回的列表是倒序的，但是页面上显示的时候，是循环这个posts，一个个输出到页面，也就是最前面的被输出到最后面。这样就是正序。

我自己把blog_lib.php的404行，改为了：array_multisort($post_dates, SORT_ASC, SORT_NUMERIC, $files);就可以了。

**Comment by hjue** [comment]
文章是按时间倒序，Position是为了实现置顶而设置的，你可以设置Position为1，表示放在第一个。
