### ISSUE TITLE
Multi-author

### ISSUE THREAD

**Issue by ncosnard** [hjue/JustWriting#54]
Hello !

It would be great to be able to specify the author for each post so we could have several writers on a single blog !

**Comment by hjue** [comment]
great idea!

**Comment by hjue** [comment]
Post meta:

    Author:hjue


The code in template:

    {{post.author}}

**Comment by ncosnard** [comment]
Awesome thanks ! :)

**Comment by ncosnard** [comment]
Is it me or it doesn't work in archive page ?
