### ISSUE TITLE
想让它支持txt格式的

### ISSUE THREAD

**Issue by bnnd** [hjue/JustWriting#55]
有个代理pac，想随时更改里面的内容，挂在网站上，需要绝对路径。
已改config.yaml文件，
 hostaccess: if(path ~ "\.(txt|md)?$") allow "127.0.0.1"

还需改哪个文件

**Comment by hjue** [comment]
blog_lib.php ,Line 257

    list($categories,$post_files) = $this->findFiles($posts_path,array('md'));

to 

    list($categories,$post_files) = $this->findFiles($posts_path,array('md','txt'));

**Comment by bnnd** [comment]
还是打开路径还是显示404.   
文件名是pac.txt    网址http://nsaos.com/post/pac和http://nsaos.com/post/pac.txt都不行

**Comment by hjue** [comment]
建议你把文件名改为 pac.md

**Comment by bnnd** [comment]
not work
