### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by tomgue** [hjue/JustWriting#56]
Hi, i have a fresh install of JW on my raspberry pi home server, but i having trouble to use JW.

i have another script like rss reader hosted, work perfectly.

[my nginx config]
(https://www.zerobin.net/?324c89e0aa94e894#nzukmVwmH7Z4Zv0J4BRpf8Bw+qeDn4QhB5zItlQxJcg=)

![capture d ecran 2015-02-07 13 56 26](https://cloud.githubusercontent.com/assets/4108018/6092168/decb4770-aed1-11e4-9a53-0c327bdd50bd.png)

Thanks Tom.

**Comment by hjue** [comment]
what's your trouble? style lost?

**Comment by tomgue** [comment]
No style, postes redirect to error
Maybe caused by nginx conf ?

**Comment by hjue** [comment]
It's my nginx config.

https://gist.github.com/hjue/647dc694dc3b67994202

**Comment by tomgue** [comment]
i have almost the [same]
(https://www.zerobin.net/?324c89e0aa94e894#nzukmVwmH7Z4Zv0J4BRpf8Bw+qeDn4QhB5zItlQxJcg=)
