### ISSUE TITLE
Dropbox fails to verify

### ISSUE THREAD

**Issue by jonathanlurie** [hjue/JustWriting#57]
Hello,

I installed JustWriting on my server (virtual, host at 1and1) and I have some trouble to make it work wit Dropbox (webhook):
I wanted to "refresh" my .md files so I've been to http://atrium.jonathanlurie.fr/sync/dropbox but I had this error:
```
Fatal error: Uncaught exception 'Exception' with message 'The Dropbox SDK uses 64-bit integers, but it looks like we're running on a version of PHP that doesn't support 64-bit integers 
```
I checked for a fix and I found that commenting the "throw" in the file application/third_party/Dropbox/RequestUtil.php on line 22 "unthrow" this error.

But then I got an error from Dropbox it self, displaying that:
````
Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.


More details for developers

Invalid redirect_uri: "http://atrium.jonathanlurie.fr/sync/dropbox/callback". When response_type=code, only localhost URIs can start with "http://"; all others must start with "https://".

```
And I have no possibility to activate ssl on my website (it's just a blog!), so I check yours at http://www.hjue.me/sync/dropbox (sorry for that) and it does not throw this ERROR 400... 
I think the fix about 64 bit-integer is not related to that.

What is you secret?  Do you have a clue to fix that?

Jonathan

**Comment by hjue** [comment]
The web hook url is http://<your_justwriting_site>/sync/dropbox/download. 

I visited the url , http://atrium.jonathanlurie.fr/sync/dropbox/download, I get a 200.

**Comment by jonathanlurie** [comment]
Ho damn I so silly!
Thanx a lot!
