### ISSUE TITLE
Add "..." after Text wrapping 

### ISSUE THREAD

**Issue by dridk** [hjue/JustWriting#58]
On the main page, content text wrap , should have some dot . 
Actually it looks like : 
     "Hello, Here is my new blog , I talk about the com"

It should be : 
         "Hello, Here is my new blog , I talk about the com ..."

**Comment by jonathanlurie** [comment]
Hi, 
did you use the `intro` keyword at the beginning? If you use it ,you can write the abstract you want and what appears on your homepage will not be a (poorly-)truncated text. You have to keep in mind the character limit (which i dont know but you can guess easily). Also, feel free to add as many dots as you want to end this abstract!  

Here is how i would write it:

```
Date: 2015-03-15    
Title: My awesome title   
Intro: Suspendisse potenti. Pellentesque tristique mi non nibh varius, a commodo orci egestas. Cras nec neque pulvinar, scelerisque massa at, malesuada est. Vestibulum aliquet nisl in ligula dictum facilisis nec sit amet dolor. Vivamus convallis mauris a augue sagittis imperdiet. Aenean id massa a enim commodo pretium. Quisque vestibulum ipsum ac sollicitudin molestie. Duis consequat felis at mauris eleifend, ac elementum orci accumsan. Nunc tincidunt ante massa, et mattis mi pretium vel. Integer ut orci sed est imperdiet pulvinar eu nec dolor........       
Tags: myTag1, myTag2  
Toc: yes   
Status: public    

```

BTW, I made few edits on my own JustWriting so I'm gonna fork it (officially) very soon :)

Cheers.

(as your 1st blog post mentions, it looks like you are not using Pelican anymore :) )

**Comment by hjue** [comment]
@jonathanlurie  good work!
