### ISSUE TITLE
简洁优秀的博客系统

### ISSUE THREAD

**Issue by siyuany** [hjue/JustWriting#61]
请问 md 文件开始的 position 是由什么用呢？
我试过，貌似不是用来设置博文顺序的

博客地址： http://www.htredleaf.com
感谢作者贡献这么优秀的博客系统！

**Comment by hjue** [comment]
感谢你对JustWriting的肯定。

文章默认是时间倒序的。如果你打算将一篇文章置顶，可以设置position为1
