### ISSUE TITLE
首页正常，但是点击文章就全是404

### ISSUE THREAD

**Issue by unhappy224** [hjue/JustWriting#62]
你好
     我将代码上传到我的空间后打开自带的文章就是404，我自己修改的setting和默认的setting都是这个问题，baseUrl我也设置了

**Comment by hjue** [comment]
如果`/index.php/post/{文章标题} （在文章地址前加index.php/)`  可以访问，说明是rewrite的问题，请查看帮助文档中关于rewrite的配置

**Comment by JellyBool** [comment]
我貌似也出现这个问题了，SAE上今天突然出事了，之前还是好好的

**Comment by JellyBool** [comment]
突然又好了！SAE是在抽风么

**Comment by hjue** [comment]
可能是抽风吧，我的也是在sae上，目前可以正常访问 http://www.hjue.me/
