### ISSUE TITLE
我用Justwriting开通了博客

### ISSUE THREAD

**Issue by hnwy** [hjue/JustWriting#64]
在虚拟空间里安装了Justwriting，可惜空间不支持Dropbox，不能用Dropbox进行更新。之前用Dropbox+Scriptogr写博客，在本地写好，只要同步一下就行，非常畅快。后来有个想法，在空间安装Bitsync，写好的博客用Bitsync更新，国内都能用，只是国内目前还没有支持Bitsync的空间。目前在研究美化一下。

site: http://unee.wang
mail: I_am@unee.wang
我发现用Justwriting的人，大多是电工，可我不是，这个博客程序已经充分好用（不考虑美化的前提下），FTP上传简单，对空间的要求小，熟悉Markdown语法的可以很方便的写，不适合第一次接触博客的人，他们更适合用Ghost或者Typecho。

**Comment by hjue** [comment]
欢迎使用JW,若有好的建议请随时联系我
