### ISSUE TITLE
能支持在Win7下安装使用么。。。

### ISSUE THREAD

**Issue by suoba** [hjue/JustWriting#66]
当是支持一下吧
1.能支持在Win7下安装使用么，尤其是写文字的时候。
2.手机呢。比如拍了张照片，显摆一下给朋友，随时随地的记录，还有视频/音频呢？
3.博客系统没有交流系统的话，除非是名人，否则就没有必要公开了，跟私人日记一样嘛。
4.敢支持手写/手绘发布么，即时手写即时显示那种，ps半天，效果图出来了，但你还有心情写么。。。
5.。。。。
。。。。
其实还有。。。
但是。。。

**Comment by JellyBool** [comment]
你其实想多了....

**Comment by hjue** [comment]
此类工具很多啊，文字图片生成私有链接，发给朋友。比如evernote
