### ISSUE TITLE
表示有好多小问题、

### ISSUE THREAD

**Issue by WildDylan** [hjue/JustWriting#67]
文章读取路径是posts 、 跳转的链接是post 、、郁闷
打建好了、 不是很全面啊、 需要自己改很多东西、希望作者完善一下、 感觉挺不错的、

WildDylan's Blog 我简书的博客 http://www.jianshu.com/users/81c4380481c1/latest_articles
http://xx-nb.cn/

**Comment by hjue** [comment]
http://xx-nb.cn/ 不能访问啊

**Comment by WildDylan** [comment]
因为我关掉了、、、

**Comment by WildDylan** [comment]
还有文章的标题读取会出错误的。  文章标题是posts 路径没问题, 但是点击文章标题跳转到界面 看到 定向的URL 变味了 xx-nb.cn/post/xxx文章、

**Comment by hjue** [comment]
posts是放md的目录，url中的post是虚拟路径，这两个没有关系
