### ISSUE TITLE
如何支持中文文件名呢？

### ISSUE THREAD

**Issue by jerecao** [hjue/JustWriting#68]
posts中，我放了一个中文文件名的文件，例如：中文.md，但是列表中能显示，点击无法打开（url地址不是类似 http://www.aaa.com/post/justwriting，而是 http://www.aaa.com/  ）。

我已经尝试下载最新的master版本了。

**Comment by hjue** [comment]
是支持中文文件名的，无法打开的原因是不是有特殊字符。

另外不建议使用中文作为文件名

**Comment by guori12321** [comment]
我写了个小脚本，可以用拼音来作为文件名，使用的时候直接`new 题目`就好。
https://gist.github.com/guori12321/679033e7345f59f698dc
里面用到几个python的库可能要安一下

和Octopress不一样，Justwriting直接用文件名来作为URL路径，所以最好的解决办法是用拼音了

**Comment by hjue** [comment]
@guori12321 非常实用的脚本
