### ISSUE TITLE
A tutorial of JustWriting Configuration

### ISSUE THREAD

**Issue by guori12321** [hjue/JustWriting#70]
I just set up my own JustWriting blog and write a tutorial about that:

http://ruiguo.me/post/2015-05-29-Yet-Another-New-Blog

But there are still lots to do. For instance, my recent post is the last one in the front page of my blog.

**Comment by hjue** [comment]
for math formulas,remove commet at the bottom of the insettings.php,then write the math formulas in the post. for example:

    $$E=mc^2$$

**Comment by guori12321** [comment]
I noticed that there is 
```
 {% for post in posts %}
```
in the `include/posts_list.html` of the `rock` template. However the default order is the oldest first, but I want the newest one first.

Is the for loop a JS or PHP? I think it's JS but I tried `posts.reverse()` and it didn't work. How to get a newest first order in this template?

Thanks!

**Comment by guori12321** [comment]
{% for post in posts | reverse %}

This is TWIG sentence, a library of PHP. And now it works.

**Comment by hjue** [comment]
Maybe something is wrong.The default order is the newest first.
[There is a demo ](http://justwriting.sinaapp.com/)

**Comment by guori12321** [comment]
I tested the original source code, and it is newest first.

What's the default order? It seems that we would look at the head information of date in the markdown posts. However, what if the two posts have the same date? Then the newly created one first?

**Comment by guori12321** [comment]
The order problem seems to be with Dropbox!

After creating a link from the Dropbox to posts, the order has changed to the oldest first.

**Comment by hjue** [comment]
It's the bug, give me some time to fix it.

**Comment by guori12321** [comment]
it seems the Dropbox returns the files ordered by the dictionary order of the file names. So I guess a recheck of the file order before we generate the home page would help.
