### ISSUE TITLE
怎么开启gzip压缩

### ISSUE THREAD

**Issue by bnnd** [hjue/JustWriting#71]
rt

**Comment by bnnd** [comment]
默认好像就是开启的，但是，我的测试没有 www.nsaos.com
https://coding.net/u/linus/p/blog/git/blob/new/application/config/config.php

![t](http://ww4.sinaimg.cn/large/6e557adagw1esnparl08tj20p20c5acs.jpg)

**Comment by hjue** [comment]
web压缩和程序无关，在web server上配置
