### ISSUE TITLE
在列表后换行不显示

### ISSUE THREAD

**Issue by fcym97** [hjue/JustWriting#75]
网页的显示效果
![image](https://cloud.githubusercontent.com/assets/8222208/8566927/05f925cc-2594-11e5-8810-c345a3c51107.png)

原文件
![image](https://cloud.githubusercontent.com/assets/8222208/8566916/f4aaa098-2593-11e5-855b-b78bb6b924e1.png)

 可以看到，有一个换行被吃掉了

**Comment by hjue** [comment]
可以把posts_list.html 中的 {{ post.intro  }} 改为 {{ post.intro|nl2br  }}

**Comment by fcym97** [comment]
确实可行！
