### ISSUE TITLE
把我的博客放到readme.md中吧

### ISSUE THREAD

**Issue by fcym97** [hjue/JustWriting#76]
使用JustWriting已经有大半年了，很棒。相比wordpress来说是一个非常非常轻快高效的博客系统。
顺便一提，能不能加入直接显示html文件的功能？我有时候要使用word来写东西，只能导出html，不能导出md文档
我的博客地址是 www.fuisblog.com

**Comment by hjue** [comment]
可以试试把.html后缀改为.md，应该可以正常显示

**Comment by fcym97** [comment]
从word导出可选mht和htm两种格式。其中mht是单文件，手动更改编码为UTF8，后缀名为md后，仍然不能正常显示，应该是内嵌了资源的缘故。导出到htm后，word会另外生成htm文件和对应的文件夹。将htm文件的编码改为UTF8后，大部分能正常显示。但是其中的斜体全部会附带格式标记，几乎不可阅读。

**Comment by hjue** [comment]
的确比较棘手，可以试试 [Word2Markdown](https://github.com/Versal/word2markdown
)

**Comment by fcym97** [comment]
我也很想用这个工具，但是我用Windows，真无奈⊙﹏⊙
