### ISSUE TITLE
关于虚拟主机上通过dropbox发布Justwriting

### ISSUE THREAD

**Issue by hnwy** [hjue/JustWriting#77]
可以再详细点吗，到了选择drop-ins app和dropbox api app，获取access token就不懂了。一直是用FTP发布，但发现不方便修改，以前也用过scriptogr.am，直接在文件夹里修改，再同步一下就行了，觉得还是用dropbox要方便些。

我的博客：http://unee.wang

**Comment by hjue** [comment]
选择dropbox api app
<img width="860" alt="screen shot 2015-08-24 at 10 16 03" src="https://cloud.githubusercontent.com/assets/1135045/9431687/4dca32f4-4a49-11e5-93f5-d0bc32052b51.png">

**Comment by hjue** [comment]
我查了你blog的ip，是国内的，可能不能调用dropbox的Api，原因你懂的

**Comment by hnwy** [comment]
主机在香港，我跟管理员联系下试试。
谢谢。

**Comment by hnwy** [comment]
关联了Dropbox后，应用文件夹里多了JW，但是空文件夹。如果正常的话，应该就会有之前写的文章了吧。

**Comment by hnwy** [comment]
以前的文章没有显示，但发表文章成功了，谢谢

**Comment by hjue** [comment]
目前用dropbox同步文章有个bug，如果电脑上删除了文章，服务器上不会删除，需要手动删除

**Comment by hjue** [comment]
也可以考虑使用dropbox客户端的方法同步文章 ， [这个是教程](https://github.com/hjue/JustWriting/wiki/%E4%BD%BF%E7%94%A8Dropbox%E5%92%8CJustwriting%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2)

**Comment by hnwy** [comment]
哦，那我进FTP删除吧。用Dropbox后，修改博文方便多了，手机安装MD编辑器并绑定dropbox，可以直接修改。目前是笔记本和手机都装了dropbox的客户端，写好的文章放进文件夹里，就会自动同步了，比起以前还要打开FTP方便，而且修改博文，就像修改本地文件一样方便。
现在就是，post这个文件夹，并没有和电脑上的完全同步，只有关联以后更新的博文的才是同步的，以前写的博文没有出现在JW文件夹里。没关系了，我自己复制进来好了，以前在scriptogr.am里都有备份。
谢谢，justwriting程序除了简陋点，主题少，其它的都很方便，除去已死的scriptogr.am和昂贵的postach.io外，是我最理想的博客方案。

**Comment by hjue** [comment]
很高兴你喜欢JustWriting :)
如果使用当中有什么问题，请随时联系我。

**Comment by hnwy** [comment]
好的，谢谢
