### ISSUE TITLE
如果添加图片,使用DropBox

### ISSUE THREAD

**Issue by yaming116** [hjue/JustWriting#78]
如果引用图片

**Comment by hjue** [comment]
在posts目录中建立images目录，然后这样引用图片

    ![Dropbox Create App](images/post/dropbox-create-app.png)

**Comment by yaming116** [comment]
图片是放在服务器上的，在 post 目录下面，那引用应该是：
```
![Dropbox Create App](post/images/dropbox-create-app.png)
```
吧

**Comment by yaming116** [comment]
怎么给图片添加统一的前缀？现在图片存在qiniu上面

**Comment by hjue** [comment]
目前不支持统一加前缀，这几天我找个时间加上

**Comment by hjue** [comment]
已经支持图片前缀，在settings.php中添加以下代码：

    $blog_config['image_prefix'] = 'xxxxxxx';

> xxxx表示前缀

**Comment by hnwy** [comment]
我的图片是放在服务器上，images/post和post/images均不能显示，/images在MD编辑器上能显示，上传至服务器，又不能显示了

**Comment by hjue** [comment]
是否设置了$blog_config['image_prefix'] ？

**Comment by hnwy** [comment]
是的。我删了试试。

**Comment by hnwy** [comment]
嗯，不行，images/post和post/images都试过，显示不了

**Comment by hnwy** [comment]
准备迁移到VPS，主机限制太多了
