### ISSUE TITLE
mysite.com works but mysite.com/blog not working

### ISSUE THREAD

**Issue by Tetsumaki** [hjue/JustWriting#79]
Hello,

I tried to use "Just Writing" but it only works on the type of URL "http(s)://site.com/ " and does not work on the type of URL "htts(s)://site.com/blog/"

The path "/" is hardcoded for the css, fonts, other...

Do you add this possibility in the future?
Have you also planned to have the choice of using the url-rewrite or not ?

Thanks :)

**Comment by hjue** [comment]
The site with apache or nginx?

**Comment by Tetsumaki** [comment]
Hello, with nginx.

**Comment by hjue** [comment]
Nginx Settings:

    server {
        listen       80;
        server_name www.justwriting.com;

        root /data/web/www.justwriting.com;
        index index.html index.php;

        # set expiration of assets to MAX for caching
        location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
                expires max;
                log_not_found off;
        }

       location ~* \.(md)$  { 
          deny all; 
        }
        
        #here changed!
        location ^~ /blog/ {
                # Check if a file exists, or route it to index.php.
                try_files $uri $uri/ /index.php$uri?$args;
        }

        location ~* \.php {

                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_split_path_info ^(.+\.php)(/?.*)$;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }


    }


settings.php

    $blog_config['base_url'] = 'http://site.com/blog';
