### ISSUE TITLE
我用Justwriting开通了博客

### ISSUE THREAD

**Issue by noidhere** [hjue/JustWriting#82]
你好，我是大家字幕组的分流组成员，目前在新浪SAE上使用Justwriting开通了资源分享博客，很感谢作者写出了JustWriting如此轻巧方便的博客程序。

目前，所有的博客md都放在posts，不知道当文件夹下的md文件增多后，会不会导致性能下降。有没有md存放的优化建议

site: http://dl.djfansub.com/
mail: dajiazimuzu@163.com

**Comment by hjue** [comment]
几千个md文件应该没有性能问题，这个数量对一般的博客足够了。再多的话可以分目录存放。

**Comment by noidhere** [comment]
想咨询个问题，在ubuntu +lnmp环境中部署，为什么dropbox同步（http://your_justwriting_site/sync/dropbox/download ）提示404？nginx配置已经按照安装说明中的配置过了。

**Comment by hjue** [comment]
如果配置好了不会这样，http://your_justwriting_site/index.php/sync/dropbox/download 这个地址是否可以访问
