### ISSUE TITLE
你好，谢谢JustWriting

### ISSUE THREAD

**Issue by isRaining** [hjue/JustWriting#83]
你好，我刚刚使用你的JustWriting，希望是一个好的旅程

**Comment by hjue** [comment]
有任何用的不爽的地方，请指出 :)

**Comment by isRaining** [comment]
**小小的问题**
* 在移动端Safari浏览器上进入到博客首页，页面不能适应屏幕。
然而进入到文章详情页都是没问题的，都可以适应屏幕。
* 点击包含汉字的标签后，页面展示,所以标签也只能是英文的吗
<br />An Error Was Encountered.The URI you submitted has disallowed characters.

使用起来很方便，我搭载在SAE上面，喜欢使用markdown来编辑文章,谢谢

**Comment by hjue** [comment]
URL是什么？

**Comment by isRaining** [comment]
[博客地址](http://1.israining.sinaapp.com)
我现在把标签都修改为英文的了，之前带汉字的标签，点击后都会错误，页面提示：*An Error Was Encountered.The URI you submitted has disallowed characters.*

还有就是希望能给博客添加一个目录的功能

**Comment by hjue** [comment]
中文标签是支持的，我的博客也是部署在SAE上的 http://www.hjue.me/tags/%E5%9F%9F%E5%90%8D。请检查一下你用的是否是最新的代码

**Comment by hjue** [comment]
可以详细描述一下你提到的目录功能吗？

**Comment by isRaining** [comment]
你好hjue！
	我指的目录功能，就像对于博客文章的一览页面。
	类似于存档的样式，我昨天刚在你的博客看到已经存在这个存档的功能，而我是在新浪SAE上直接安装的JustWriting，我的博客内没有这个存档的标签和对应的页面，对于web开发我不是很熟练，所以我想也能够有，不知道该怎么做，这个博客的主题很简洁，也很喜欢，谢谢您的提供。

**Comment by hjue** [comment]
新浪SAE上的版本比较老了，一直没有更新。

用github上最新的代码覆盖就可以了。记得备份你的文章(posts)和settings.php

**Comment by isRaining** [comment]
您好hjue,justWriting怎么添加多说的评论功能,我现在用的github上pull下的代码，放在新浪sae上。

**Comment by hjue** [comment]
在多说上添加应用，得到shortname，在settings.php中进行设置

```
$blog_config['comment'] = True;

//duoshuo short name，duoshuo is the social comment system,url is  http://duoshuo.com/.

$blog_config['duoshuo_short_name'] = 'justwriting';

```

**Comment by isRaining** [comment]
谢谢，已经搞定
