### ISSUE TITLE
VPS主页能打开，页面404

### ISSUE THREAD

**Issue by hnwy** [hjue/JustWriting#86]
SORRY，又来麻烦你了。
正在迁移至国外的VPS，原来的虚拟空间还能正常用，但限制太多。有一个VPS用来上网，并给朋友建了个小站，PHP，运行正常，正准备把现博客迁移过去。
现在的情况是，主页能打开，但是页面404，坐标暂时 http://t.unee.wang
服务器用的是LNMP，上传博客计划用btsync，目前都已架设好。chown -R www:www posts/,chown -R www:www application/cache，这两个命令都用了，重启过nginx。

**Comment by hnwy** [comment]
nginx.conf换成你提供的，主页也打不开了。悲剧。

**Comment by hjue** [comment]
应该是nginx配置的不正确,如何不配置nginx的话
http://t.unee.wang/index.php/post/justwriting，这个地址可以访问

**Comment by hnwy** [comment]
是不是PHP需要安装什么东西，我没有装上

**Comment by hnwy** [comment]
不管配置不配置，下面的页面都不能访问，但是主页能打开。
http://t.unee.wang/index.php/post/justwriting
现在猜测是不是PHP少了什么扩展，PHP安装是默认的lnmp.org脚本。

**Comment by qoli** [comment]
重寫有沒有打開？在 httpd.conf 改。

**Comment by hnwy** [comment]
一语惊醒我，静态页面都可以，添加网站时提示我rewrite，我选择的否。我是nginx，我再看看，谢谢

**Comment by hnwy** [comment]
用作者的配置文件就是502，用默认的，主页能打开，页面404。求一个你们能用的配置文件

**Comment by hnwy** [comment]
问题解决，是PHP端口问题，改到9000就好了
