### ISSUE TITLE
怎样在windows上同步文章？

### ISSUE THREAD

**Issue by zhaobinhong** [hjue/JustWriting#88]
windows上用dorpbox的时候会提示要用64位的php才可以，但是貌似windows没有64位的php  。这该怎么整？

**Comment by hjue** [comment]
有提示的截图吗？

**Comment by zhaobinhong** [comment]
![113144](https://cloud.githubusercontent.com/assets/14801442/11621505/b6f13290-9cf7-11e5-9fdb-1ec3f2fe111f.png)

**Comment by hjue** [comment]
PHP有windows64位的版本 http://windows.php.net/download#php-5.5
