### ISSUE TITLE
linux 跳转页面报404

### ISSUE THREAD

**Issue by zhaobinhong** [hjue/JustWriting#89]
![image](https://cloud.githubusercontent.com/assets/14801442/11675785/ab98ef3e-9e67-11e5-870a-6a5064d78c13.png)

windows上可以正常跳转linux 上就报路径错误这是怎么回事

**Comment by hjue** [comment]
/index.php/post/justwriting 是否可以正常访问？

**Comment by zhaobinhong** [comment]
![image](https://cloud.githubusercontent.com/assets/14801442/11678309/7c4a24b8-9e81-11e5-884b-53acf300a851.png)
可以 没有问题

**Comment by hjue** [comment]
你没有正确配置Apache，参考Readme配置

**Comment by zhaobinhong** [comment]
![image](https://cloud.githubusercontent.com/assets/14801442/11708345/4ced27e2-9f49-11e5-8a52-be7035031c55.png)


这个是需要怎么配置？

**Comment by hjue** [comment]
php需要配置curl这个模块

**Comment by zhaobinhong** [comment]
![image](https://cloud.githubusercontent.com/assets/14801442/11710814/f00564a4-9f5c-11e5-9cdb-db9aa383b248.png)
为什么会有这么多错  
为什么这么难

**Comment by zhaobinhong** [comment]
这个怎么解决？

**Comment by hjue** [comment]
参考这篇文章：windows 下 php 下curl 扩展库的安装 
http://www.oschina.net/question/17_44

**Comment by camus0129** [comment]
在linux下我也遇到跳转页面404了，/index.php/post/justwriting 也可以正常访问

**Comment by hjue** [comment]
@camus0129 ,是服务器配置rewrite的问题，请参考readme文档进行配置

**Comment by camus0129** [comment]
@hjue 我仔细检查了apache的配置以及rewrite模块加载情况，包括文件夹的读写权限，依然还是有问题，readme文件文档里面关于apache.conf的配置两种配置都尝试过了，也不行。
目前环境是ubuntu14.04 + apache2+ php5

**Comment by camus0129** [comment]
@hjue 反复修改了apache的虚拟主机的配置文件，将你给出的两个配置文件结合起来，终于成功了

**Comment by mspwang** [comment]
@camus0129 我也遇到这个问题了，能否分享你结合起来的配置文件？多谢！

**Comment by mspwang** [comment]
In case more people hit this problems, just for your reference. 

got this issue fixed by adding those in apache config file (sites-enabled/000-default.conf):
```
        RewriteEngine on
        RewriteCond $1 !^(index\.php|css|styles|posts|images|templates|robots\.txt)
        RewriteCond %{REQUEST_URI} !^.*(\.css|\.js|\.gif|\.png|\.jpg|\.jpeg)$
        RewriteRule ^(.*)$ /index.php?/$1 [L]
```


If have following issues when restarting apache2:
> Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration
> Action 'configtest' failed.
> The Apache error log may have more information.

Follow those steps to enable apache 2 rewrite_module:
Apache 2 on Ubuntu is a bit different than some servers, as Apache is usually controlled in the /etc/apache2 directory.
```
cd /etc/apache2/mods-enabled
ln -s ../mods-available/rewrite.load rewrite.load
```
in /etc/apache2/sites-available folder edit the configuration of the site,
change “AllowOverride none“ to “AllowOverride all“

**Comment by zhaobinhong** [comment]
我的这个问题是因为被墙了  

zhaobinhong29@163.com

发件人： Simpeng
发送时间： 2016-04-22 01:26
收件人： hjue/JustWriting
抄送： zhaobinhong; Author
主题： Re: [hjue/JustWriting] linux 跳转页面报404 (#89)
@camus0129 我也遇到这个问题了，能否分享你结合起来的配置文件？多谢！

**Comment by simpeng** [comment]
@zhaobinhong 多谢你的回复！我遇到的问题是文章页面无法显示（404），但是像hjue说的/index.php/post/justwriting 可以正常访问。我按照apache的第二种配置做了，成功了。原来不行是因为我忘记把之前在网站root下面加的.htaccess删掉了。:)
