### ISSUE TITLE
JustWriting 做得很棒，反馈个小问题

### ISSUE THREAD

**Issue by hwen** [hjue/JustWriting#91]
你好 hjue 
比如我想增加一个“分类”功能？大概要怎么做？

还有想问的是 JustWriting 后台的 api 写在哪里，哪些文件？（我没接触过 PHP，所以不太清楚）

**Comment by hwen** [comment]
最后自己捣鼓了下...
1.增加了分类，分页
2.更改在移动端显示样式
3.本来还想加个搜索功能的...有时间再弄吧

PS： 发现个问题，highlight.pack.js 的加载时间太长，在 chrome 下调试，首次（强制刷新）加载，highlight.pack.js 的加载时间一般消耗 6-10s。建议使用者自己去定制：https://highlightjs.org/download/
只下载自己需要的语法。

我的博客（测试）：http://3.bynoth.sinaapp.com/

**Comment by hjue** [comment]
@hwen :+1:  很强啊

**Comment by hwen** [comment]
见笑了，还是只是个菜鸟，虽然实现了功能但代码写得不太好看 T_T
