### ISSUE TITLE
我写的JustWriting的教程

### ISSUE THREAD

**Issue by hnwy** [hjue/JustWriting#93]
http://unee.wang/post/20151229justwriting
http://unee.wang/post/20151230justwriting
计划正传三篇，目前写了两篇，还有一个正在写，快要上班了，不敢造次。写好后链接应该是
http://unee.wang/post/20151231justwriting

写这个的原因是，自己在配置的过程中走了很多弯路，而且，作者太！懒！了！第三篇可能在下班的时候继续，内容是通过btsync发布博客。

**Comment by hjue** [comment]
谢谢你的分享。抱歉，对Web Server的配置介绍的不多，让你走了些弯路。
